---
title: "A Scorecard Example"
author: "Shichen Xie"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Vignette Title}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r, fig.height=3, fig.width=6}
# load packages
library(data.table)
library(scorecard)

# load germancredit data
data("germancredit")

# rename creditability as y, and replace bad/good by 1/0
dt = setDT(germancredit)[,`:=`(
  y = ifelse(creditability=="bad", 1, 0),
  creditability = NULL
)]
dim(dt)

# calculate information value 
ivdt = iv(dt, "y")
ivdt[,info_value := round(info_value,4)][]

# filter variable via missing rate, iv, identical value rate
dt_s = var_filter(dt, "y")
dim(dt_s)
# the variables removed
var_filter(dt, "y", return_rm_reason = TRUE)$rm

# breaking dt into train and test ------
dt_list = split_df(dt_s, y="y", ratio = 0.6, seed = 180)
train = dt_list$train; test = dt_list$test;

# woe binning ------
bins = woebin(dt_s, "y", print_step = 0)
bins[[1]]

# binning plot
woebin_plot(bins[[1]])

# binning adjustment
# breaks_adj = woebin_adj(bins, dt_s, "y") # adjust breaks interactively
breaks_adj = 
  list(
    status.of.existing.checking.account=c("... < 0 DM%,%0 <= ... < 200 DM", "... >= 200 DM / salary assignments for at least 1 year", "no checking account"), 
    duration.in.month=c(8, 16, 36, 40), 
    credit.history=c("no credits taken/ all credits paid back duly%,%all credits at this bank paid back duly", "existing credits paid back duly till now%,%delay in paying off in the past", "critical account/ other credits existing (not at this bank)"), 
    purpose=c("retraining%,%car (used)", "radio/television", "furniture/equipment%,%domestic appliances%,%business%,%repairs%,%car (new)%,%others%,%education"), 
    credit.amount=c(1400, 4000, 7800), 
    savings.account.and.bonds=c("... < 100 DM", "100 <= ... < 500 DM", "500 <= ... < 1000 DM%,%... >= 1000 DM%,%unknown/ no savings account"), 
    present.employment.since=c("unemployed%,%... < 1 year", "1 <= ... < 4 years", "4 <= ... < 7 years", "... >= 7 years"), 
    installment.rate.in.percentage.of.disposable.income=c(3), 
    personal.status.and.sex=c("female : divorced/separated/married", "male : single", "male : married/widowed"), 
    other.debtors.or.guarantors=c("none", "co-applicant%,%guarantor"), 
    property=c("real estate", "building society savings agreement/ life insurance", "car or other, not in attribute Savings account/bonds", "unknown / no property"), 
    age.in.years=c(26, 35, 37), 
    other.installment.plans=c("bank%,%stores", "none"), 
    housing=c("rent", "own", "for free")
) 
bins_adj = woebin(dt_s,"y", breaks_list=breaks_adj, print_step = 0)
woebin_plot(bins_adj[[1]])

# converting train and test into woe values
train_woe = woebin_ply(train, bins_adj, print_step = 0)
test_woe = woebin_ply(test, bins_adj, print_step = 0)

# glm ------
## logistic regression
m1 = glm( y ~ ., family = "binomial", data = train_woe)
# summary(m1)

## Select a formula-based model by AIC
m_step = step(m1, direction="both", trace = FALSE)
m2 = eval(m_step$call)
# summary(m2)

# performance ------
## predicted proability
train_pred = predict(m2, train_woe, type='response')
test_pred = predict(m2, test_woe, type='response')

## ks & roc plot
train_perf = perf_eva(train$y, train_pred, title = "train")
test_perf = perf_eva(test$y, test_pred, title = "test")

## create scorecard
card = scorecard(bins_adj, m2)
class(card)
# rbindlist(card, fill=TRUE)

## convert original data into credit score
train_score = scorecard_ply(train, card, print_step = 0)
test_score = scorecard_ply(test, card, print_step = 0)

## population stability index
perf_psi(
  score = list(train = train_score, test = test_score),
  label = list(train = train$y, test = test$y),
  x_limits = c(250, 700),
  x_tick_break = 50
  )

```

